export const SET_LIST_JOB_TYPE_MENU = "SET_LIST_JOB_TYPE_MENU"; // MENU

export const SET_CHI_TIET_LOAI_CONG_VIEC = "SET_CHI_TIET_LOAI_CONG_VIEC";

export const SET_CONG_VIEC_THEO_CHI_TIET_LOAI = "SET_CONG_VIEC_THEO_CHI_TIET_LOAI";

export const SET_CONG_VIEC_CHI_TIET = "SET_CONG_VIEC_CHI_TIET";

export const SET_DANH_SACH_CONG_VIEC_THEO_TEN = "SET_DANH_SACH_CONG_VIEC_THEO_TEN";
